### ISSUE TITLE
Show text when :button is clicked

### ISSUE THREAD

**Issue by sergioro9** [AndyObtiva/glimmer-dsl-libui#58] opened 2023-09-01 19:59 UTC
I would like "hello world" to be displayed below the button when the button is clicked. I tried this but nothing happens when I click the button:

```ruby
body do
  button("Test button") {
    on_clicked do
      sample_text
    end
  }
end

def sample_text
  label {
    text 'hello world'
  }
end

```

**Comment by AndyObtiva** [comment] 2023-09-01 20:25
When relying on `Glimmer::LibUI::Application`, it is assumed that the `body` block would have a `window` first as the parent of everything.

Also, if you just render a `label` as in `sample_text`, but inside an `on_clicked` listener block, it won't go anywhere. It needs to be added to the `content` of a parent control in order to show up.

In any case, there are multiple solutions to your problem, included below.

1- Include button and label from the start, and when button is clicked, update label text via data-binding

```ruby
require 'glimmer-dsl-libui'

class ShowLabel
  include Glimmer::LibUI::Application
  
  attr_accessor :label_text
  
  body {
    window('Show Label 1') {
      margined true
      
      vertical_box {
        button('Show Label') {
          on_clicked do
            self.label_text = 'hello world'
          end
        }
        label {
          text <= [self, :label_text]
        }
      }
    }
  }
end

ShowLabel.launch
```

<img width="190" alt="Screenshot 2023-09-01 at 4 19 15 PM" src="https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/e6987bbd-23b8-4211-896e-a84f9e9c983c">
<img width="190" alt="Screenshot 2023-09-01 at 4 19 17 PM" src="https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/f580ca9e-0c10-4a5a-9df4-a8b6b2293373">

2- Include button only in the beginning, and when button is clicked, add label to the content of its parent vertical_box (if the button is clicked again, do nothing)

```ruby
require 'glimmer-dsl-libui'

class ShowLabel
  include Glimmer::LibUI::Application
  
  body {
    window('Show Label 2') {
      margined true
      
      vertical_box { |label_box|
        button('Show Label') {
          on_clicked do
            unless @label_shown
              label_box.content {
                label {
                  text 'hello world'
                }
              }
              @label_shown = true
            end
          end
        }
      }
    }
  }
end

ShowLabel.launch
```

<img width="190" alt="Screenshot 2023-09-01 at 4 21 18 PM" src="https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/517de211-1bdd-4fdd-ad3a-c94bbe31d070">
<img width="190" alt="Screenshot 2023-09-01 at 4 21 21 PM" src="https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/f75ca48c-d560-41f0-8dbf-f79f0b4c7319">

2- Include button only in the beginning, and when button is clicked, destroy button and replace it by adding a label to the content of its parent vertical_box

```ruby
require 'glimmer-dsl-libui'

class ShowLabel
  include Glimmer::LibUI::Application
  
  body {
    window('Show Label 3') {
      margined true
      
      vertical_box { |label_box|
        button('Show Label') { |show_label_button|
          on_clicked do
            unless @label_shown
              show_label_button.destroy
              label_box.content {
                label {
                  text 'hello world'
                }
              }
              @label_shown = true
            end
          end
        }
      }
    }
  }
end

ShowLabel.launch
```

<img width="190" alt="Screenshot 2023-09-01 at 4 23 01 PM" src="https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/9bacd383-3e81-4048-96bb-6ae9f0efee36">
<img width="190" alt="Screenshot 2023-09-01 at 4 23 03 PM" src="https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/fa75daad-3b4e-497b-ac2f-f4c8a6a58207">

I am closing this issue assuming I answered your question. If I did not answer your question fully or you have other questions, feel free to reply even if the issue is closed. I will see your replies anyways and will respond further here or even reopen the issue if needed.

**Closed by AndyObtiva** 2023-09-01 20:25 UTC

**Comment by sergioro9** [comment] 2023-09-01 22:26
Thank you, your examples were clear and answered my question.

The first version of my GUI app is ready, but I don't know how to publish it in Windows, MacOS, Linux. Is there any website to learn how to publish GUI apps?

**Comment by AndyObtiva** [comment] 2023-09-01 22:42
I’m glad I answered your question. 

I have not done enough work to support packaging on different platforms yet. But, there is a Packaging section in the README with some information about native executable packaging for different platforms:
https://github.com/AndyObtiva/glimmer-dsl-libui#packaging

On Windows, there is a new tool to help build a Windows executable:
https://github.com/Largo/ocran

If you discover better ways of packaging, you can report back and contribute to the README. 

Cheers.

**Comment by AndyObtiva** [comment] 2023-09-04 20:44
I just remembered that there is a new way to package Ruby applications on all platforms via Ruby WASM WASI. I haven’t tested it yet, but maybe you can try it if needed. I added it to the packaging section of the project README. Below is the direct link. 

https://github.com/ruby/ruby.wasm#quick-example-how-to-package-your-ruby-application-as-a-wasi-application
