### ISSUE TITLE
[reopen] Cannot update fill of a circle

### ISSUE THREAD

**Issue by phuongnd08** [AndyObtiva/glimmer-dsl-libui#50] opened 2023-05-29 05:43 UTC
I couldn't re-open an issue that I think unsolved, so link it here for attention: https://github.com/AndyObtiva/glimmer-dsl-libui/issues/49

**Comment by AndyObtiva** [comment] 2023-05-29 22:55
You are using `scrolling_area` instead of `area`, but the same solution applies.

Here is a working code sample with stable paths:

```ruby
require 'glimmer-dsl-libui'

include Glimmer

window('Circle Random Coloring by Clicking', 400, 400) {
  scrolling_area {
    circle(200, 200, 90) { |c| # declarative stable path (implicit path syntax for a single shape nested directly under area)
      fill r: 202, g: 102, b: 204, a: 0.5
      stroke r: 0, g: 0, b: 0, thickness: 2
      
      on_mouse_up do
        c.fill = [rand(255), rand(255), rand(255)]
      end
    }
  }
}.show
```

![glimmer-dsl-libui-circle_random_coloring_by_clicking](https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/109bc286-2a96-4aaf-960f-f1b9dc73dc86)


Here is the example re-written with dynamic paths:

```ruby
require 'glimmer-dsl-libui'

include Glimmer

window('Circle Random Coloring by Clicking', 400, 400) {
  @area = scrolling_area {
    on_draw do |area_draw_params|
      @circle = circle(200, 200, 90) { |c| # declarative stable path (implicit path syntax for a single shape nested directly under area)
        fill r: rand(255), g: rand(255), b: rand(255), a: 0.5
        stroke r: 0, g: 0, b: 0, thickness: 2
      }
    end
    
    on_mouse_up do |mouse_event|
      @area.queue_redraw_all if @circle.contain?(mouse_event[:x], mouse_event[:y])
    end
  }
}.show
```

https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/28afcf86-f972-427a-9f46-6ee439bf11fd


Please let me know if either example's code helps you resolve your issue.

**Comment by AndyObtiva** [comment] 2023-05-29 22:57
OK, I think I found the culprit in your code from https://github.com/AndyObtiva/glimmer-dsl-libui/issues/49:

```ruby
scrolling_area {
    text {
      indicator = string

      controller.on_stat_updated do |controller|
        indicator.string = controller.indication
      end
    }

    color_indicator = nil
    color_area = area {
      color_indicator =  circle(200, 200, 90) { # declarative stable path (implicit path syntax for a single shape nested directly under area)
        stroke r: 0, g: 0, b: 0, thickness: 2
        fill <= controller.color
      }
    }
```

You are nesting an `area {` within a `scrolling_area {`! That's wrong! You must choose to either use an `area` or a `scrolling_area`. There is no need to nest an `area` inside `scrolling_area`, so you can nest the `circle` directly under `scrolling_area`, and that should resolve your issue.

**Comment by phuongnd08** [comment] 2023-05-30 01:15
okay, so I can see that if I use mouse_up to set the color, it's effective. if I call code from a thread, it's not effective.

Here is the code:

```
    circle(200, 200, 90) do |color_indicator| # declarative stable path (implicit path syntax for a single shape nested directly under area)
      stroke r: 0, g: 0, b: 0, thickness: 2
      fill controller.color

      on_mouse_up do
        color_indicator.fill = [rand(255), rand(255), rand(255)]
      end

      Thread.new {
        loop do
          puts "fill with random color"
          color_indicator.fill = [rand(255), rand(255), rand(255)]
          sleep 1
        end
      }
```

if things run correctly, I am supposed to see a new color whenever I click on the circle, or every seconds.  But I only see new color when I click on the circle. There are log in the terminal confirming the thread is running:
```
fill with random color
fill with random color
fill with random color
fill with random color
fill with random color
fill with random color
fill with random color
fill with random color
```

**Comment by phuongnd08** [comment] 2023-05-30 01:17
Adding queue_redraw_all doesn't help:

```
    circle(200, 200, 90) do |color_indicator| # declarative stable path (implicit path syntax for a single shape nested directly under area)
      stroke r: 0, g: 0, b: 0, thickness: 2
      fill controller.color

      on_mouse_up do
        color_indicator.fill = [rand(255), rand(255), rand(255)]
      end

      Thread.new {
        loop do
          puts "fill with random color"
          color_indicator.fill = [rand(255), rand(255), rand(255)]
          @area&.queue_redraw_all
          sleep 1
        end
      }
  end
```

**Comment by AndyObtiva** [comment] 2023-05-30 01:43
Yes, that's because if you're updating from a different Thread, you have to wrap all your calls to the GUI with `Glimmer::LibUI.queue_main { ... }` in order to access the main GUI thread (documented under [LibUI Operations](https://github.com/AndyObtiva/glimmer-dsl-libui#libui-operations) and used in [Glimmer Meta-Example](https://github.com/AndyObtiva/glimmer-dsl-libui/blob/master/examples/meta_example.rb)). Also, you don't need `area.queue_redraw_all` if you are using stable paths (e.g. nesting `circle` directly under `area` or `scrolling_area`).

This updated sample updates the `circle` `fill` color from a `Thread` (it also demonstrates the new recommended way of building Glimmer DSL for LibUI applications by taking advantage of the `Glimmer::LibUI::Application` mixin, which provides a `.launch` method and `before_body`/`after_body` hooks that execute before and after building the GUI `body`):

```ruby
require 'glimmer-dsl-libui'

include Glimmer

class CircleRandomColoringByThread
  include Glimmer::LibUI::Application
  
  after_body do
    Thread.new {
      loop do
        puts "fill with random color"
        Glimmer::LibUI.queue_main do
          @circle.fill = [rand(255), rand(255), rand(255)]
        end
        sleep 1
      end
    }
  end
  
  body {
    window('Circle Random Coloring by Clicking', 400, 400) {
      scrolling_area {
        @circle = circle(200, 200, 90) { |c| # declarative stable path (implicit path syntax for a single shape nested directly under area)
          fill r: 202, g: 102, b: 204, a: 0.5
          stroke r: 0, g: 0, b: 0, thickness: 2
          
          on_mouse_up do
            c.fill = [rand(255), rand(255), rand(255)]
          end
        }
      }
    }
  }
end

CircleRandomColoringByThread.launch
```

![glimmer-dsl-libui-circle_random_coloring_by_thread](https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/d1092a5c-a74e-4551-bbe4-1b914bb05dfb)

If you are updating indirectly through a model, you still have to wrap the update call to the model with `Glimmer::LibUI.queue_main { ... }`.

Please confirm if this resolves your issue in order to close it.

Cheers.

**Comment by phuongnd08** [comment] 2023-05-30 06:36
Thanks, my bad for not reading through the documentation. Though, my though is either recommend every UI update to go through something link update_ui block (i.e update_ui { code }), and update_ui is an alias of queue_main under the hook, or design it so that the update automatically use queue_main as a convention so developer don't have to worry about this in their code. If this has a performance penalty, allow the developer to config this to not be a default behavior to speed up the app if they intend to do something seriously with it later?

**Comment by AndyObtiva** [comment] 2023-05-30 16:12
Yeah, I actually automated this requirement completely in Glimmer DSL for SWT, which has an equivalent to queue_main called async_exec. After a certain version release, developers don’t need to use async_exec explicitly in Glimmer DSL for SWT anymore when running from a different thread. It happens automatically for them.

I will consider similarly automating the use of queue_main from other threads in Glimmwr DSL for LibUI. The library is relatively new, so I didn’t get a chance to do it. I’m adding this task to the TODO list. 

Otherwise, I am closing this issue. If you have further comments or questions, feel free to reply. I will see your comments even if the issue is closed.

**Closed by AndyObtiva** 2023-05-30 16:12 UTC
